### ISSUE TITLE
Сесюритя, пользователи, вайтлист

### ISSUE THREAD

**Issue by quicklybly** [burunyuu23/tagger#14]
База с пользователями: id_vk | _**List<Роль>**_
Роль: id | Название_роли

Если пользователя нет в базе, то считать его за ROLE_ANONYMOUS
Если пользователь есть в базе, то сразу считать его за ROLE_USER
Роли: ANONYMOUS, USER, **_ADMIN, GROUP, ~~BLOCKED~~ TEST_** // Помеченные должны быть в базе

// Справка по именованию в вк библиотеке
fromId - id написавшего пользователя
peerId - то откуда пришло сообщение

**Comment by burunyuu23** [comment]
Добавлены проверки ролей на контроллеры. Также в каждом методе контроллера возвращается текущий User?. 

Если User null (нет в базе) соответствует ANONYMOUS (всем контроллерам и методам без @TaggerMappingRole())
Если User есть и у него нет ролей соответствует USER (всем контроллерам и методам с @TaggerMappingRole([]) пустым массивом ролей) + ANONYMOUS
BLOCKED заменён на TEST (для тестеров каких нибудь команд)
Остальные роли проверяются на наличие у user

Если уровень прав не соответствует, то ответом будет "У вас нет доступа" или что-то типа того
+ help возвращает только те методы и контроллеры куда у пользователя есть доступ

**Comment by burunyuu23** [comment]
Возможно стоит сделать чтобы уровень прав наращивался, т.е. проверялся самый глубокий уровень прав (чтобы можно было закрыть контроллер ролью ADMIN, но разрешить метод для ANONYMOUS (выглядит странно, но вдруг сфера применения будет шире чем я думаю))

**Comment by quicklybly** [comment]
мрку делаем, а не вот эта подвальная разработка 

> Возможно стоит сделать чтобы уровень прав наращивался, т.е. проверялся самый глубокий уровень прав (чтобы можно было закрыть контроллер ролью ADMIN, но разрешить метод для ANONYMOUS (выглядит странно, но вдруг сфера применения будет шире чем я думаю))
